-- Metric : Customer Lifetime Revenue
-- Period : Customer Lifetime
-- Description : Calculates the total revenue generated by each customer over their lifetime.
select
    c.customer_id,
    c.customer_name,
    round(
        sum(
            pv.selling_price * od.quantity * (1 - coalesce(od.discount_percentage, 0) / 100)
        ),
        2
    ) as customer_lifetime_revenue
from
    product_variants as pv
    inner join order_details as od on pv.variant_id = od.variant_id
    inner join orders as o on o.order_id = od.order_id
    inner join customers as c on c.customer_id = o.customer_id
group by
    c.customer_id,
    c.customer_name;

-- Metric : Customer Lifetime Orders
-- Period : Customer Lifetime
-- Description : Calculates the total number of orders placed by each customer over their lifetime.
select
    c.customer_id,
    c.customer_name,
    count(o.order_id) as customer_lifetime_orders
from
    orders as o
    inner join customers as c on c.customer_id = o.customer_id
group by
    c.customer_id,
    c.customer_name
order by
    customer_lifetime_orders desc;

-- Metric : Customer Lifetime Profit
-- Period : Customer Lifetime
-- Description : Calculates the total gross profit generated by each customer over their lifetime.
select
    c.customer_id,
    c.customer_name,
    round(
        sum(
            (
                pv.selling_price * od.quantity * (1 - coalesce(od.discount_percentage, 0) / 100)
            ) - (pv.cost_price * od.quantity)
        ),
        2
    ) as customer_lifetime_profit
from
    product_variants as pv
    inner join order_details as od on pv.variant_id = od.variant_id
    inner join orders as o on o.order_id = od.order_id
    inner join customers as c on c.customer_id = o.customer_id
group by
    c.customer_id,
    c.customer_name
order by
    customer_lifetime_profit desc;

-- Metric : Average Revenue per Customer
-- Period : Customer Lifetime
-- Description : Calculates the average lifetime revenue generated per purchasing customer.
select
    round(
        sum(
            pv.selling_price * od.quantity * (1 - coalesce(od.discount_percentage, 0) / 100)
        ) / count(distinct o.customer_id),
        2
    ) as average_revenue_per_customer
from
    product_variants as pv
    inner join order_details as od on pv.variant_id = od.variant_id
    inner join orders as o on o.order_id = od.order_id;

-- Metric : Customer Revenue Contribution Percentage
-- Period : Customer Lifetime
-- Description : Calculates each customer's percentage contribution to total customer lifetime revenue.
select
    c.customer_id,
    c.customer_name,
    round(
        (
            sum(
                pv.selling_price * od.quantity * (1 - coalesce(od.discount_percentage, 0) / 100)
            ) * 100
        ) / (
            select
                sum(
                    pv.selling_price * od.quantity * (1 - coalesce(od.discount_percentage, 0) / 100)
                )
            from
                product_variants as pv
                inner join order_details as od on pv.variant_id = od.variant_id
                inner join orders as o on o.order_id = od.order_id
        ),
        4
    ) as customer_revenue_contribution_percentage
from
    product_variants as pv
    inner join order_details as od on pv.variant_id = od.variant_id
    inner join orders as o on o.order_id = od.order_id
    inner join customers as c on c.customer_id = o.customer_id
group by
    c.customer_id,
    c.customer_name
order by
    customer_revenue_contribution_percentage desc;

-- Metric : Customer Gross Profit Contribution Percentage
-- Period : Customer Lifetime
-- Description : Calculates each customer's percentage contribution to total customer lifetime gross profit.
select
    c.customer_id,
    c.customer_name,
    round(
        (
            sum(
                (
                    pv.selling_price * od.quantity * (1 - coalesce(od.discount_percentage, 0) / 100)
                ) - (pv.cost_price * od.quantity)
            ) * 100
        ) / (
            select
                sum(
                    (
                        pv.selling_price * od.quantity * (1 - coalesce(od.discount_percentage, 0) / 100)
                    ) - (pv.cost_price * od.quantity)
                )
            from
                product_variants as pv
                inner join order_details as od on pv.variant_id = od.variant_id
                inner join orders as o on o.order_id = od.order_id
        ),
        4
    ) as customer_gross_profit_contribution_percentage
from
    product_variants as pv
    inner join order_details as od on pv.variant_id = od.variant_id
    inner join orders as o on o.order_id = od.order_id
    inner join customers as c on c.customer_id = o.customer_id
group by
    c.customer_id,
    c.customer_name
order by
    customer_gross_profit_contribution_percentage desc;

-- Metric : Average Order Value per Customer
-- Period : Customer Lifetime
-- Description : Calculates the average order value generated by each customer over their lifetime.
select
    c.customer_id,
    c.customer_name,
    round(
        sum(
            pv.selling_price * od.quantity * (1 - coalesce(od.discount_percentage, 0) / 100)
        ) / count(distinct o.order_id),
        2
    ) as average_order_value
from
    product_variants as pv
    inner join order_details as od on pv.variant_id = od.variant_id
    inner join orders as o on o.order_id = od.order_id
    inner join customers as c on c.customer_id = o.customer_id
group by
    c.customer_id,
    c.customer_name
order by
    average_order_value desc;

-- Metric : Top 10 Customers by Revenue
-- Period : Customer Lifetime
-- Description : Identifies the top 10 customers based on total lifetime revenue generated.
with customer_revenue_rank_table as (
    select
        c.customer_id,
        c.customer_name,
        round(
            sum(
                pv.selling_price * od.quantity * (1 - coalesce(od.discount_percentage, 0) / 100)
            ),
            2
        ) as customer_lifetime_revenue,
        rank() over (
            order by
                sum(
                    pv.selling_price * od.quantity * (1 - coalesce(od.discount_percentage, 0) / 100)
                ) desc
        ) as revenue_rank
    from
        product_variants as pv
        inner join order_details as od on pv.variant_id = od.variant_id
        inner join orders as o on o.order_id = od.order_id
        inner join customers as c on c.customer_id = o.customer_id
    group by
        c.customer_id,
        c.customer_name
)
select
    customer_id,
    customer_name,
    customer_lifetime_revenue
from
    customer_revenue_rank_table
where
    revenue_rank <= 10
order by
    revenue_rank asc;

-- Metric : Top 10 Customers by Gross Profit
-- Period : Customer Lifetime
-- Description : Identifies the top 10 customers based on total lifetime gross profit generated.
with customer_profit_rank_table as (
    select
        c.customer_id,
        c.customer_name,
        round(
            sum(
                (
                    pv.selling_price * od.quantity * (1 - coalesce(od.discount_percentage, 0) / 100)
                ) - (pv.cost_price * od.quantity)
            ),
            2
        ) as customer_lifetime_gross_profit,
        rank() over (
            order by
                sum(
                    (
                        pv.selling_price * od.quantity * (1 - coalesce(od.discount_percentage, 0) / 100)
                    ) - (pv.cost_price * od.quantity)
                ) desc
        ) as gross_profit_rank
    from
        product_variants as pv
        inner join order_details as od on pv.variant_id = od.variant_id
        inner join orders as o on o.order_id = od.order_id
        inner join customers as c on c.customer_id = o.customer_id
    group by
        c.customer_id,
        c.customer_name
)
select
    customer_id,
    customer_name,
    customer_lifetime_gross_profit
from
    customer_profit_rank_table
where
    gross_profit_rank <= 10
order by
    gross_profit_rank asc;

-- Metric : Bottom 10 Customers by Revenue
-- Period : Customer Lifetime
-- Description : Identifies the bottom 10 purchasing customers based on total lifetime revenue generated.
with customer_revenue_rank_table as (
    select
        c.customer_id,
        c.customer_name,
        round(
            sum(
                pv.selling_price * od.quantity * (1 - coalesce(od.discount_percentage, 0) / 100)
            ),
            2
        ) as customer_lifetime_revenue,
        rank() over (
            order by
                sum(
                    pv.selling_price * od.quantity * (1 - coalesce(od.discount_percentage, 0) / 100)
                ) asc
        ) as revenue_rank
    from
        product_variants as pv
        inner join order_details as od on pv.variant_id = od.variant_id
        inner join orders as o on o.order_id = od.order_id
        inner join customers as c on c.customer_id = o.customer_id
    group by
        c.customer_id,
        c.customer_name
)
select
    customer_id,
    customer_name,
    customer_lifetime_revenue
from
    customer_revenue_rank_table
where
    revenue_rank <= 10
order by
    revenue_rank asc;

-- Metric : Top Revenue Contributors (80/20 Pareto Analysis)
-- Period : Customer Lifetime
-- Description : Identifies the highest-revenue customers whose cumulative contribution does not exceed 80% of the total customer lifetime revenue.
with customer_revenue_rank_table as (
    select
        c.customer_id,
        c.customer_name,
        round(
            sum(
                pv.selling_price * od.quantity * (1 - coalesce(od.discount_percentage, 0) / 100)
            ),
            2
        ) as customer_lifetime_revenue,
        rank() over (
            order by
                sum(
                    pv.selling_price * od.quantity * (1 - coalesce(od.discount_percentage, 0) / 100)
                ) desc
        ) as revenue_rank
    from
        product_variants as pv
        inner join order_details as od on pv.variant_id = od.variant_id
        inner join orders as o on o.order_id = od.order_id
        inner join customers as c on c.customer_id = o.customer_id
    group by
        c.customer_id,
        c.customer_name
),
customer_cummulative_revenue_table as (
    select
        customer_id,
        customer_name,
        customer_lifetime_revenue,
        revenue_rank,
        sum(customer_lifetime_revenue) over (
            order by
                customer_lifetime_revenue desc
        ) as cummulative_customer_revenue,
        round(
            (
                (
                    sum(customer_lifetime_revenue) over (
                        order by
                            customer_lifetime_revenue desc
                    )
                ) * 100
            ) / (
                select
                    round(
                        sum(
                            pv.selling_price * od.quantity * (1 - coalesce(od.discount_percentage, 0) / 100)
                        ),
                        2
                    ) as total_revenue
                from
                    product_variants as pv
                    inner join order_details as od on pv.variant_id = od.variant_id
                    inner join orders as o on o.order_id = od.order_id
            ),
            2
        ) as cummulative_revenue_percentage
    from
        customer_revenue_rank_table
    order by
        revenue_rank asc
)
select
    *
from
    customer_cummulative_revenue_table
where
    cummulative_revenue_percentage <= 80;